on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  fetch_docs:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    name: A job to update the docs
    steps:
      - name: Fetch Docs
        id: hello
        uses: jrr997/actions-test@dev
        with:
          ref: "master"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
          branch: output
